name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install package and test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run unit tests
        run: pytest -q

      # ------------------------------------------------------------
      # Execute Jupyter notebooks headlessly and save output to /tmp
      # ------------------------------------------------------------
      - name: Execute notebooks
        run: |
          pip install jupyter nbconvert matplotlib
          for nb in notebooks/*.ipynb; do
              jupyter nbconvert --to notebook --execute "$nb" \
                --ExecutePreprocessor.timeout=900 \
                --output-dir /tmp
          done
