name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install package + test extras
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[test]"

      - name: Run unit tests
        run: |
          pytest -q
