# ---------- .github/workflows/ci.yml ----------------------
name: CI

on:
  push:
    branches: [ "main", "ci/**", "feat/**", "fix/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-notebooks:
    runs-on: ubuntu-latest

    steps:
      # checkout ------------------------------------------------------------
      - uses: actions/checkout@v4

      # Python --------------------------------------------------------------
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Cache pip -----------------------------------------------------------
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}

      # Install project + all extras ---------------------------------------
      - name: Install package (editable) with all CI extras
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test,notebook]"

      # Unit tests ----------------------------------------------------------
      - name: Run pytest quietly
        run: pytest -q

      # Execute notebooks ---------------------------------------------------
      - name: Execute notebooks
        run: |
          mkdir -p paper/figs build/nb
          for nb in notebooks/*.ipynb; do
            echo "▶ Executing $nb"
            jupyter-nbconvert "$nb" --to notebook --execute \
              --ExecutePreprocessor.timeout=600 \
              --output-dir build/nb
          done

      # Upload executed notebooks as artefact ------------------------------
      - name: Upload executed notebooks
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebooks
          path: build/nb
