name: CI

on:
  push:
    branches: [ "main", "ci/**", "feat/**", "fix/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Cache PIP
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml', 'requirements*.txt') }}

    # 🔑  everything we need, including Jupyter + nbconvert
    - name: Install project (test + notebook extras)
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[test,notebook]"

    # ────────────────────────────────────
    # UNIT TESTS
    # ────────────────────────────────────
    - name: Run pytest
      run: |
        pytest -q

    # ────────────────────────────────────
    # EXECUTE NOTEBOOKS  → HTML kept as build artefacts
    # ────────────────────────────────────
    - name: Execute notebooks
      run: |
        set -e
        mkdir -p paper/figs build/nb
        for nb in notebooks/*.ipynb; do
          echo "▶ Executing $nb"
          jupyter-nbconvert "$nb" --to notebook --execute \
            --ExecutePreprocessor.timeout=600 \
            --output "build/nb/$(basename "$nb")"
        done

    - name: Upload executed notebooks
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebooks
        path: build/nb
