
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install
      run: |
        pip install -e .
        pip install pytest
    - name: Test
      run: pytest -q
    - name: Execute notebooks
      run: |
        pip install jupyter nbconvert matplotlib
        for nb in notebooks/*.ipynb; do
            jupyter nbconvert --to notebook --execute "$nb" \
                --ExecutePreprocessor.timeout=600 --output /dev/null
          done

