name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, ci/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"   # repo uses 3.10

    - name: Install package + test extras
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[test]"

    - name: Run unit tests
      run: pytest -q

      # Execute notebooks
       # Execute notebooks
    - name: Execute notebooks
      run: |
        set -e
      # ➊ create output dirs so notebooks can save figures
        mkdir -p paper/figs build/nb
      # ➋ execute each notebook, drop the executed copy in build/nb/
        for nb in notebooks/*.ipynb; do
          jupyter-nbconvert \
            --to notebook --execute "$nb" \
            --output-dir build/nb      # <-- here
        done
