# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, ci/fix-pytest, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 🧪 Unit tests
    runs-on: ubuntu-latest

    steps:
      # ---------- checkout ----------------------------------------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- set up Python ----------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # ---------- install package + test deps ---------------------------------
      - name: Install package (editable) with test extras
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]"

      # ---------- run pytest --------------------------------------------------
      - name: Run pytest quietly
        run: |
          pytest -q

  notebooks:
    name: 📓 Execute notebooks
    runs-on: ubuntu-latest
    needs: test        # only run if tests pass

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[notebook]"     # will pick up jupyter, matplotlib, …

      - name: Execute notebooks
        run: |
          mkdir -p paper/figs build/nb
          for nb in notebooks/*.ipynb; do
            echo "▶ Executing $nb"
            jupyter-nbconvert --to notebook --execute "$nb" --output-dir build/nb
          done
